version: '3.8'

services:
  frontend:
    build:
      context: ./dashboard-sgi
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL:-http://localhost:5801/api}

