version: '3.8'

services:
  frontend:
    build:
      context: https://github.com/jpxdpt/SGI.git#master
      dockerfile: dashboard-sgi/Dockerfile
      args:
        # Define a URL do backend durante o build
        # Substitui IP_DO_SERVIDOR pelo IP do teu servidor onde o backend está a correr
        VITE_API_BASE_URL: http://IP_DO_SERVIDOR:5801/api
    container_name: sgi-frontend
    ports:
      - "8081:80"
    environment:
      # Variável de ambiente para runtime (usa window.__ENV__ se disponível)
      # Se o backend está na mesma stack, usa: http://backend:5801/api
      # OU se o backend está exposto externamente: https://sgi-backend.loca.lt/api
      - VITE_API_BASE_URL=http://IP_DO_SERVIDOR:5801/api
    restart: unless-stopped

